Hotfixes `pytest-*` plugins to include `py`
AnacondaRecipes/repodata-hotfixes pull request #193
Opened 2023-05-16 20:07 UTC by schuylermartin45

**Changes**
- Full details/context can be found in the code comments
- tl;dr Many `pytest-*` plugins transitively included `py` via `pytest` so when `pytest` took the dependency out in v7.2.0, several plugins broke. There are so many plugins we are just assuming this affects all of them to get a fix out the door for damage control. We know of at least two so far that have this issue.

**Issues Encountered**
- N/A

2023-05-16 20:09 UTC, schuylermartin45 commented
Here is the output from my local. I think these diffs look safe/are what we want. I skimmed it, so I could have easily missed something in the thousands of lines
[repodata_pytest.txt](https://github.com/AnacondaRecipes/repodata-hotfixes/files/11491640/repodata_pytest.txt)

2023-05-16 20:17 UTC, marcoesters requested changes

2023-05-16 20:17 UTC, marcoesters commented on main.py
> +        replace_dep(depends, "", "py", append=True)
I think this needs a guard. `pytest-html-3*` now has both `py` and `py >=1.8.2` in the diff. We don't want to clobber over already existing dependencies.

2023-05-16 20:23 UTC, schuylermartin45 commented on main.py
> +        replace_dep(depends, "", "py", append=True)
Good catch, searching `py` is a freakin pain with this one. Fortunately I think that's the only case where that happens(?)

2023-05-16 20:25 UTC, schuylermartin45 commented on main.py
> +        replace_dep(depends, "", "py", append=True)
I guess it also isn't clear to me if `replace_dep()` should be intelligent enough to prevent that, but that's a discussion for another time

2023-05-16 20:48 UTC, marcoesters approved these changes

2023-05-16 20:49 UTC, Callek commented on main.py
> +            if dep == "py" or dep.startswith("py "):
I'm not aware of the syntax space for `dep` but would `dep` ever be `py>foo` `py<foo` `py==foo` in this code?

2023-05-16 21:04 UTC, schuylermartin45 commented on main.py
> +            if dep == "py" or dep.startswith("py "):
I thought the ` ` was required before the operator and enforced somewhere. So I did a quick test and the linter doesn't enforce it and conda build doesn't seem to care either.

Good catch, this is what I get for making assumptions.

2023-05-17 15:14 UTC, Callek commented on main.py
> +            if re.match(r"py(<|>|=|\s|$)", dep):
Looks like you need `!` and `~` per https://peps.python.org/pep-0440/#version-specifiers

And while `\s` catches it, its worth just mentioning that `py 1.2` is also valid as an alternative for `==`

2023-05-17 15:24 UTC, schuylermartin45 commented on main.py
> +            if re.match(r"py(<|>|=|\s|$)", dep):
After our previous discussion, I figured `\s` was safer than trying to regex whitespace and a version number.

That's good to know this is a standard somewhere. I didn't know who defined these ops. `!=` is an interesting case, presumably it is almost always followed by some other version information.

2023-05-17 20:18 UTC, ELundby45 approved these changes

2023-05-17 20:18 UTC, merged

2023-05-17 20:19 UTC, schuylermartin45 commented
Merged to resolve customer impact