add numpy 2 hotfix to main
AnacondaRecipes/repodata-hotfixes pull request #227
Opened 2024-06-14 13:31 UTC by JamesRobertsonGames

numpy 2 pinnings for any packages that do not have an upper bound 

### Links

- [PKG-4837](https://anaconda.atlassian.net/browse/PKG-4837) 

### Explanation of changes:
- Add pinings for numpy2

2024-06-17 18:48 UTC, cbouss commented on main.py
> +                updated = True
I see in the output lines like "numpy-base 1.11.3 py27hdbf6ddf_8", replaced by "numpy-base 1.11.3 py27hdbf6ddf_8,<2.0a0",. The upper bound is added on the hash, which I expect to cause trouble, but most of all, we don't need to add upper bounds to packages pinned to a specific version.

2024-06-17 18:48 UTC, cbouss commented on main.py
> +        if dep.startswith("numpy"):
```suggestion
        if dep.split()[0] == "numpy":
```
Otherwise it will also match numpy-base, numpydoc...

2024-06-17 18:48 UTC, cbouss commented on main.py
> +        if dep.startswith("numpy-base") and '==' not in dep and '<' not in dep:
```suggestion
        if dep.split()[0] == "numpy-base" and '==' not in dep and '<' not in dep:
```

2024-06-17 18:48 UTC, cbouss commented on main.py
> +        elif dep == "numpy-base":
```suggestion
        else:
```

2024-06-18 11:19 UTC, JamesRobertsonGames commented
@cbouss thanks for the review, made the suggestions and reuploaded the most upto date output

2024-06-18 18:27 UTC, cbouss commented on main.py
> +            updated = True
This causes all dependencies to be replaced by numpy-base

2024-06-19 13:14 UTC, JamesRobertsonGames commented
Much better output now in the output.txt @cbouss

2024-06-20 14:51 UTC, cbouss commented
Besides the diff it would be great to have some analysis on the repodata before and after the patch. I feel this would help ensure all is covered.

Also, I have been thinking, what if we publish this patch, then start building python packages with no upper bounds (because they support numpy 2), and someone regenerate a patch? A <1 bound would be wrongfully added. So perhaps instead we could have a configuration file like:
```
pandas: 2.2.2,
scikit-lear: 1.4.2,
...
```
Which could be used to patch like (pseudo code):
```
if pkg in numpy2_protect_dict:
  if VersionOrder(version) <= VersionOrder(numpy2_protect_dict['version']):
    add_dep(numpy < 2.0a0)
```
This way if needed we can tweak the configuration file and retain more control.

2024-06-27 14:39 UTC, JamesRobertsonGames commented on main.py
> +    numpy2_protect_dict = yaml.safe_load(f)
My only concern is it is likely to be fairly long? I could add it in a new python file (which just has a giant dict) and include that? This `main.py` is already bloated and long I don't really want to add so 100's of lines potentially (it's 3 at the moment but we haven't compiled the final list)

2024-06-27 18:03 UTC, Jrice1317 commented on main.py
> +    numpy2_protect_dict = yaml.safe_load(f)
I agree adding pyyaml does seem a bit like overkill for this single usage. Perhaps since `json` is already being imported, that can be utilized here?

2024-06-28 08:06 UTC, JamesRobertsonGames commented on main.py
> +    numpy2_protect_dict = yaml.safe_load(f)
`json` wasn't selected just because it's slightly less human readable, might as well go forward with a dict in a separate file I think that strikes the balance, and if I do end up writing a script to generate it I can still do that with a separate .py file

2024-07-25 17:17 UTC, cbouss reviewed
Did a quick first pass

2024-07-25 17:17 UTC, cbouss commented on README.md
> +4. Generates a `proposed_numpy_changes.json` file containing all proposed changes.
Can you rename `proposed_numpy_changes.json` to `numpy2_patch.json`? Since this file is checked in and will remain this will be clearer.

2024-07-25 17:17 UTC, cbouss commented on main.py
> +        with open('proposed_numpy_changes.json', 'r') as f:
Not having this file should fail the script.

2024-07-25 17:17 UTC, cbouss commented on main.py
> +
```suggestion
```
I don't see that function being used.

2024-07-25 17:17 UTC, cbouss commented on main.py
> +def apply_numpy_changes(record, subdir, filename):
Can you make it more explicit? Perhaps just replacing numpy by numpy2.

2024-07-25 17:17 UTC, cbouss commented on numpy2.py
> +    "win-64",
```suggestion
    "noarch",
    "linux-64",
    "linux-aarch64",
    "linux-s390x",
    "osx-64",
    "osx-arm64",
    "win-64",
```
Only need to work on what we support today.

2024-07-25 17:17 UTC, cbouss commented on numpy2.py
> +            if "py39" in fn or "py310" in fn or "py311" in fn or "py312" in fn:
```suggestion
            # numpy 2 is introduced for python 3.9. Packages for python 3.13 will be built with numpy2 from the start.
            if "py39" in fn or "py310" in fn or "py311" in fn or "py312" in fn:
```

2024-07-25 17:17 UTC, cbouss commented on numpy2.py
> +            if "py39" in fn or "py310" in fn or "py311" in fn or "py312" in fn:
This leaves noarch packages out though. Perhaps that's fine.

2024-07-26 16:01 UTC, cbouss commented on numpy2_patch.json
Can you generate it avoiding the case where no update actually occurs?
I mean removing entries like:
```
    "adtk-0.6.2-py310h2f386ee_0.tar.bz2": [
      {
        "type": "dep",
        "original": "numpy >=1.21.5,<2.0a0",
        "updated": "numpy >=1.21.5,<2.0a0",
        "reason": "Already has upper bound"
      }
    ],
```

2024-07-26 16:45 UTC, JamesRobertsonGames commented on numpy2_patch.json
Done and regenerated the file 👍

2024-07-29 14:18 UTC, ryanskeith requested changes
After thinking on this over the weekend, I feel there are two major things to ask for (if I understand the code correctly).

First, let's simplify numpy2.py code.
- Let's rename to generate_numpy2.py changes
- Remove all code not being used and most reporting type code.
- Simplify the data structure in the numpy2_patch.json
- Move testing code to the tests folder

Second, let's simplify the incorporation of the numpy2 patches into main.py
- Remove any logging or side product reporting
- Use standard dep replacement code

2024-07-29 14:18 UTC, ryanskeith commented on main.py
> +    changes = NUMPY_2_CHANGES[subdir][filename]
You can then refer to subdir_changes from above.

2024-07-29 14:18 UTC, ryanskeith commented on main.py
> +def _apply_changes_to_dependencies(depends, change, record, filename, sort_type='reason'):
```suggestion
def _apply_changes_to_dependencies(depends_or_constraints, change, record, filename, sort_type='reason'):
```

2024-07-31 08:40 UTC, JamesRobertsonGames commented on numpy2.py
> +        if package_name in ["numpy", "numpy-base"]:
As discussed: this is correct right now as we have not properly populated the protected versions

2024-08-01 11:14 UTC, JamesRobertsonGames commented
@cbouss @ryanskeith 

Should have addressed the comments, the output is looking good on the test-hotfix.py to me, removed all non-essential logging and simplified the solution based on the suggestions. Let me know if I have missed anything or anything new is observed :)

2024-08-01 16:04 UTC, ryanskeith commented on main.py
> +def _get_dependency_list(record, change_type):
I don't think this warrants its own function.  If you store "depends" and "constrains" directly in the numpy2_patch.json file, the replace_dep line becomes:

```
replace_dep(record[change["change_type"]], change["original"], change["updated"]
```

Your process already did all the cleaning so we shouldn't have any weird third cases.

2024-08-01 16:05 UTC, ryanskeith commented on main.py
> +def _get_dependency_list(record, change_type):
This also gets rid of the unnecessary for loop.

2024-08-01 16:06 UTC, ryanskeith commented on main.py
> +    if NUMPY_2_CHANGES:
As stated before, as this block changes many different files and NOT a targeted file.  It should be run last.

2024-08-02 15:51 UTC, ryanskeith requested changes
This is progressing quite well.  A couple things.

- I think we can safely drop "numpy-base" from the list as it has never been triggered
  - This should simplify the logic in places so you can directly ask and not have to do the reverse.
- I think as this code has a lot of nested if/else statements, you need more comments inline as the logic is hard to follow.  My gut tells me there is still some simplifications that should occur.
  - Specifically more comments for generate_numpy2_patch:update_numpy_dependencies and :main
- Lastly, how are you checking for no arch again?  the filename will not work in the noarch case.

2024-08-02 15:51 UTC, ryanskeith commented on generate_numpy2_patch.py
> +                    if version and protected_version:
ah, I see.

2024-08-02 15:51 UTC, ryanskeith commented on main.py
> +        try:
In what case do you feel that you will have a failure when you have been given a filename the record will fail?  I don't think you need to be so protective here.

2024-08-02 15:51 UTC, ryanskeith commented on generate_numpy2_patch.py
> +                                update_numpy_dependencies(depends, record, "dep", subdir, fn)
```suggestion
                                update_numpy_dependencies(depends, record, "depends", subdir, fn)
```

2024-08-02 15:51 UTC, ryanskeith commented on generate_numpy2_patch.py
> +                                update_numpy_dependencies(constrains, record, "constr", subdir, fn)
```suggestion
                                update_numpy_dependencies(constrains, record, "constrains", subdir, fn)
```

2024-08-02 15:51 UTC, ryanskeith commented on generate_numpy2_patch.py
> +    if change_type == "dep":
By giving the full change_type on creation, you don't need this if else statement.

2024-08-02 15:51 UTC, ryanskeith commented on main.py
> +    # Numpy 2.0.0 Patch
Needs comments on what this does.

2024-08-02 15:51 UTC, ryanskeith commented on main.py
> +    else:
We don't need an else in this case.

2024-08-02 15:51 UTC, ryanskeith commented on generate_numpy2_patch.py
> +    with json_filename.open('w') as f:
Not necessary but this can be a one liner.
```suggestion
    json_filename.write_text(json.dumps(dict(NUMPY_2_CHANGES), indent=2)
```

2024-08-08 09:44 UTC, JamesRobertsonGames commented
@ryanskeith done your suggestions, on the noarch I think a previous review concluded that there is little point doing noarch in this instance? @cbouss if you have an opinion on this feel free to wade in! Happy to handle this edge case, or we could deploy without this and then rectify the noarch packages in another PR?

2024-08-09 14:04 UTC, cbouss commented
> @ryanskeith done your suggestions, on the noarch I think a previous review concluded that there is little point doing noarch in this instance? @cbouss if you have an opinion on this feel free to wade in! Happy to handle this edge case, or we could deploy without this and then rectify the noarch packages in another PR?

Yes I believe it is best to not patch noarch packages, at least for now. I am not sure of which edge cases this would uncover, and it is now time to release numpy 2.

2024-08-09 14:05 UTC, cbouss approved these changes
LGTM!

2024-08-12 18:35 UTC, ryanskeith approved these changes
Looks good.  You could remove the dead code in `generate_numpy2_patch.py`, but it isn't necessary.

2024-08-12 18:35 UTC, ryanskeith commented on generate_numpy2_patch.py
> +    if change_type == "dep":
You can get rid of lines 55-58 now.

2024-08-13 13:55 UTC, merged